# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-15 20:51
from __future__ import unicode_literals

from django.db import migrations

def create_initial_users(apps,schema_editor):
    User = apps.get_model('catalog','User')
    User(name="Juan Perez", uid=0).save()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
